database:
  host: "localhost"
  port: 5432
  user: "url"
  password: "97243057"
  name: "gorm"
  retry: 4
  retryTimeOut: 6
httpHandler:
  port: 8080
  workers: 3
log:
  level: "debug"
redis:
  host: "localhost"
  port: 6379
  password: "97243057"
  DB: 0
  TTL: 1
  retry: 4
  retryTimeOut: 6