database:
  host: mysql
  port: 3306
  user: "root"
  password: "mysql"
  name: "shortener"
  retry: 4
  retryTimeOut: 6
httpHandler:
  port: 8080
  workers: 3
log:
  level: "debug"
redis:
  host: redis
  port: 6379
  DB: 0
  TTL: 1
  retry: 4
  retryTimeOut: 6